### ISSUE TITLE
App crash when I come back from background

### ISSUE THREAD

**Issue by inveders** [GetStream/stream-video-android#1194]
**Describe the bug**
Hello,
I've implemented getstream for livestreaming in my app. I'm using Jetpack Compose. I have a live page and a podcast page. So I don't even enter the live page, I go to the podcast page, then I put my app in the background. When I come back to the app, it crashes and gives me this message.

`
java.lang.IllegalStateException: User token is empty
                                                                                                    	at io.getstream.video.android.core.socket.CoordinatorSocket.authenticate(CoordinatorSocket.kt:64)
                                                                                                    	at io.getstream.video.android.core.socket.PersistentSocket$connect$3$2$2.invokeSuspend(PersistentSocket.kt:136)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cfbfc67, Dispatchers.IO]
`

**SDK version**
- 1.0.14
io.getstream:stream-video-android-ui-compose:1.0.14

**To Reproduce**
1. Implement getstream in your app
2. Put the app in background
3. Come back in the app

**Expected behavior**
The app come from backgorund without any issue

**Device:**
 - Vendor and model: Samsung A34
 - Android version: Android 14

**Comment by aleksandar-apostolov** [comment]
Hey @inveders 

The `userToken` must never be null or empty. You should only initialise the SDK if you have a user and its token. 
Can you please provide a sample code of how is the SDK initialised on your side especially with regards to the user, token and any token provider you may have.

Regards,
Alex
