### ISSUE TITLE
suddenly I started to get this crash :java.lang.IllegalArgumentException: width must be positive 

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#847]
how to fix this? why I get this? java.lang.IllegalArgumentException: width must be positive
                                                                                                    	at com.android.internal.util.Preconditions.checkArgumentPositive(Preconditions.java:279)
                                                                                                    	at android.hardware.camera2.params.StreamConfigurationDuration.<init>(StreamConfigurationDuration.java:58)
                                                                                                    	at android.hardware.camera2.marshal.impl.MarshalQueryableStreamConfigurationDuration$MarshalerStreamConfigurationDuration.unmarshal(MarshalQueryableStreamConfigurationDuration.java:68)
                                                                                                    	at android.hardware.camera2.marshal.impl.MarshalQueryableStreamConfigurationDuration$MarshalerStreamConfigurationDuration.unmarshal(MarshalQueryableStreamConfigurationDuration.java:45)
                                                                                                    	at android.hardware.camera2.marshal.impl.MarshalQueryableArray$MarshalerArray.unmarshal(MarshalQueryableArray.java:93)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.getBase(CameraMetadataNative.java:869)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.getBase(CameraMetadataNative.java:833)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.getStreamConfigurationMap(CameraMetadataNative.java:1597)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.access$400(CameraMetadataNative.java:96)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative$5.getValue(CameraMetadataNative.java:907)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:733)
                                                                                                    	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:696)
                                                                                                    	at android.hardware.camera2.CameraCharacteristics.get(CameraCharacteristics.java:249)
                                                                                                    	at org.webrtc.Camera2Enumerator.getSupportedFormats(Camera2Enumerator.java:180)
                                                                                                    	at org.webrtc.Camera2Enumerator.getSupportedFormats(Camera2Enumerator.java:157)
                                                                                                    	at org.webrtc.Camera2Enumerator.getSupportedFormats(Camera2Enumerator.java:80)
                                                                                                    	at io.getstream.video.android.core.CameraManager.sortDevices$stream_video_android_core_release(MediaManager.kt:674)
                                                                                                    	at io.getstream.video.android.core.CameraManager.setup$stream_video_android_core_release(MediaManager.kt:636)
                                                                                                    	at io.getstream.video.android.core.CameraManager.enable(MediaManager.kt:492)
                                                                                                    	at io.getstream.video.android.core.CameraManager.setEnabled(MediaManager.kt:519)
                                                                                                    	at io.getstream.video.android.core.CameraManager.setEnabled$default(MediaManager.kt:517)
                                                                                                    	at io.getstream.video.android.core.Call.updateMediaManagerFromSettings(Call.kt:833)
                                                                                                    	at io.getstream.video.android.core.Call.join(Call.kt:303)
                                                                                                    	at io.getstream.video.android.core.Call$join$1.invokeSuspend(Unknown Source:18)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8057)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@5c1f6a6, androidx.compose.runtime.BroadcastFrameClock@720c8e7, StandaloneCoroutine{Cancelling}@fd61c94, AndroidUiDispatcher@957733d]

**Comment by DanielNovak** [comment]
Thanks for reporting this issue.

It's crashing inside this `sortDevices()` function in CameraManager: https://github.com/GetStream/stream-video-android/blob/dc1df6f6bac245e3581f0ae78f674eedd27e3cb7/stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/MediaManager.kt#L658

And this line crashes - which is an Android Camera 2 API call:
```
            val supportedFormats = enumerator.getSupportedFormats(id)
```

It seems like for one specific camera on that device the width is 0 - but that sounds like a platform bug 🤔 . Are you able to reproduce it? What device model is it?

I found some Huawei issues with the camera with the same crash:
https://c.mi.com/us/thread-3152605-1-0.html?mobile=no

**Comment by razaghimahdi** [comment]
> Thanks for reporting this issue.
> 
> It's crashing inside this `sortDevices()` function in CameraManager:
> 
> https://github.com/GetStream/stream-video-android/blob/dc1df6f6bac245e3581f0ae78f674eedd27e3cb7/stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/MediaManager.kt#L658
> 
> And this line crashes - which is an Android Camera 2 API call:
> 
> ```
>             val supportedFormats = enumerator.getSupportedFormats(id)
> ```
> 
> It seems like for one specific camera on that device the width is 0 - but that sounds like a platform bug 🤔 . Are you able to reproduce it? What device model is it?
> 
> I found some Huawei issues with the camera with the same crash: https://c.mi.com/us/thread-3152605-1-0.html?mobile=no

Hi there, tnx for the response. device model is Xiaomi Redmi note 8, I noticed that camera of phone sometimes doesn't work, but I believe still stream shouldn't crash.

**Comment by DanielNovak** [comment]
Yes, that is a valid point. We can catch the exception, log it and then ignore this specific camera (e.g. if front camera doesn't work, maybe back camera will work). This could be a simple workaround. Adding @aleksandar-apostolov to this.

**Comment by aleksandar-apostolov** [comment]
Hi, we merged the fix. It will be included in the next release.
