### ISSUE TITLE
java.lang.NullPointerException   at io.getstream.video.android.core.CallState

### ISSUE THREAD

**Issue by razaghimahdi** [GetStream/stream-video-android#882]
on version 0.3.4 i get this:

java.lang.NullPointerException
                                                                                                    	at io.getstream.video.android.core.CallState.updateFromJoinResponse(CallState.kt:853)
                                                                                                    	at io.getstream.video.android.core.CallState.handleEvent(CallState.kt:685)
                                                                                                    	at io.getstream.video.android.core.StreamVideoImpl.fireEvent$stream_video_android_core_release(StreamVideoImpl.kt:487)
                                                                                                    	at io.getstream.video.android.core.call.RtcSession$listenToSocket$1$1.emit(RtcSession.kt:340)
                                                                                                    	at io.getstream.video.android.core.call.RtcSession$listenToSocket$1$1.emit(RtcSession.kt:339)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8082604, Dispatchers.IO]
                                                                                                    	

why? how to fix this?

**Comment by DanielNovak** [comment]
Hi @razaghimahdi , this was fixed in https://github.com/GetStream/stream-video-android/pull/879. It's a backend change that was recently done. The `started_at` field isn't populated anymore.

**Comment by skydoves** [comment]
Hey @razaghimahdi we released a new version `0.4.0` and it contains the bug fix as Daniel mentioned. Thank you for reporting this issue. If you still face the same problem on the latest version, please re-open this issue.
